create table if not exists public.jokes (
  id bigint generated by default as identity primary key,
  setup text not null unique,
  punchline text not null,
  created_at timestamptz not null default now()
);

alter table public.jokes enable row level security;

drop policy if exists "Jokes are publicly readable" on public.jokes;

create policy "Jokes are publicly readable"
on public.jokes
for select
to anon, authenticated
using (true);

insert into public.jokes (setup, punchline)
values
  ('Why did the developer go broke?', 'Because they used up all their cache.'),
  ('Why do programmers prefer dark mode?', 'Because light attracts bugs.'),
  ('What is a database developer''s favorite snack?', 'A structured query linguine.')
on conflict (setup) do nothing;
